import ActionTypes from '../constants/actionTypes';

export const setVip = payload => ({ type: ActionTypes.SET_VIP, payload });
export const logOut = payload => ({ type: ActionTypes.LOG_OUT, payload });
export const setLike = payload => ({ type: ActionTypes.SET_LIKE, payload });
export const sendGift = payload => ({ type: ActionTypes.SEND_GIFT, payload });
export const blockUser = payload => ({ type: ActionTypes.BLOCK_USER, payload });
export const stopTimer = payload => ({ type: ActionTypes.STOP_TIMER, payload });
export const clearStore = payload => ({ type: ActionTypes.CLEAR_STORE, payload });
export const reportUser = payload => ({ type: ActionTypes.REPORT_USER, payload });
export const initConfig = payload => ({ type: ActionTypes.INIT_CONFIG, payload });
export const changeRout = payload => ({ type: ActionTypes.CHANGE_ROUT, payload });
export const deleteLiker = payload => ({ type: ActionTypes.DELETE_LIKER, payload });
export const unblockUser = payload => ({ type: ActionTypes.UNBLOCK_USER, payload });
export const startTimers = payload => ({ type: ActionTypes.START_TIMERS, payload });
export const setRegState = payload => ({type: ActionTypes.SET_REG_STATE, payload});
export const initUrlPath = payload => ({ type: ActionTypes.INIT_URL_PATH, payload });
export const saveDataToLS = payload => ({ type: ActionTypes.SAVE_DATA_TO_LS, payload });
export const setUserState = payload => ({type: ActionTypes.SET_USER_STATE, payload});
export const getMeRequest = payload => ({ type: ActionTypes.GET_ME_REQUEST, payload });
export const setMainState = payload => ({type: ActionTypes.SET_MAIN_STATE, payload});
export const setNewAvatar = payload => ({ type: ActionTypes.SET_NEW_AVATAR, payload });
export const checkTokenLs = payload => ({ type: ActionTypes.CHECK_TOKEN_LS, payload });
export const setEmailValue = payload => ({type: ActionTypes.SET_EMAIL_VALUE, payload});
export const deleteContent = payload => ({ type: ActionTypes.DELETE_CONTENT, payload });
export const setFriendsTab = payload => ({ type: ActionTypes.SET_FRIENDS_TAB, payload });
export const youAreBlocked = payload => ({type: ActionTypes.YOU_ARE_BLOCKED, payload});
export const initIndexedDb = () => ({ type: ActionTypes.INIT_INDEXED_DB });
export const setUserProfile = payload => ({type: ActionTypes.SET_USER_PROFILE, payload});
export const setUserCountry = payload => ({type: ActionTypes.SET_USER_COUNTRY, payload});
export const setButtonState = payload => ({type: ActionTypes.SET_BUTTON_STATE, payload});
export const setChangeEmail = payload => ({ type: ActionTypes.SET_CHANGE_EMAIL, payload });
export const setMissedMatch = payload => ({type: ActionTypes.SET_MISSED_MATCH, payload});
export const getGiftsByUser = payload => ({ type: ActionTypes.GET_GIFTS_BY_USER, payload });
export const setConfigStore = payload => ({ type: ActionTypes.SET_CONFIG_STORE, payload });
export const setUploadPhoto = payload => ({ type: ActionTypes.SET_UPLOAD_PHOTO, payload });
export const setAvatarStore = payload => ({ type: ActionTypes.SET_AVATAR_STORE, payload });
export const manageUserData = payload => ({ type: ActionTypes.MANAGE_USER_DATA, payload });
export const verifyLinkEmail = payload => ({ type: ActionTypes.VERIFY_LINK_EMAIL, payload });
export const setIsLimitStore = payload => ({ type: ActionTypes.SET_IS_LIMIT_STORE, payload });
export const getLikesRequest = payload => ({ type: ActionTypes.GET_LIKES_REQUEST, payload });
export const setSideMenuMode = payload => ({ type: ActionTypes.SET_SIDE_MENU_MODE, payload });
export const openModalWindow = payload => ({ type: ActionTypes.OPEN_MODAL_WINDOW, payload });
export const setPasswordValue = payload => ({type: ActionTypes.SET_PASSWORD_VALUE, payload});
export const setInputTextPass = payload => ({type: ActionTypes.SET_INPUT_TEXT_PASS, payload});
export const sendReportParams = payload => ({ type: ActionTypes.SEND_REPORT_PARAMS, payload });
export const setRootComponent = payload => ({ type: ActionTypes.SET_ROOT_COMPONENT, payload });
export const setAnchorElStore = payload => ({ type: ActionTypes.SET_ANCHOR_EL_STORE, payload });
export const removeDataFromLS = payload => ({ type: ActionTypes.REMOVE_DATA_FROM_LS, payload });
export const setUserDataStore = payload => ({ type: ActionTypes.SET_USER_DATA_STORE, payload });
export const setWindowScrollY = payload => ({ type: ActionTypes.SET_WINDOW_SCROLL_Y, payload });
export const setGiftsListData = payload => ({ type: ActionTypes.SET_GIFTS_LIST_DATA, payload });
export const setBothLikesData = payload => ({ type: ActionTypes.SET_BOTH_LIKES_DATA, payload });
export const setUnlikeRequest = payload => ({ type: ActionTypes.SET_UNLIKE_REQUEST, payload});
export const setRegStateStore = payload => ({type: ActionTypes.SET_REG_STATE_STORE, payload});
export const setInputBirthday = payload => ({type: ActionTypes.SET_INPUT_BIRTHDAY_VALUE, payload});
export const setInputTextEmail = payload => ({type: ActionTypes.SET_INPUT_TEXT_EMAIL, payload});
export const setMainStateStore = payload => ({type: ActionTypes.SET_MAIN_STATE_STORE, payload});
export const setUserEmailStore = payload => ({type: ActionTypes.SET_USER_EMAIL_STORE, payload});
export const setInputTextStore = payload => ({type: ActionTypes.SET_INPUT_TEXT_STORE, payload});
export const setUserStateStore = payload => ({type: ActionTypes.SET_USER_STATE_STORE, payload});
export const setMyProfileState = payload => ({ type: ActionTypes.SET_MY_PROFILE_STATE, payload });
export const setPageEventsData = payload => ({ type: ActionTypes.SET_PAGE_EVENTS_DATA, payload });
export const dislekeMutualLike = (payload, userId) => ({ type: ActionTypes.DISLEKE_MUTUAL_LIKE, payload, userId });
export const setIconsPathStore = payload => ({type: ActionTypes.SET_ICONS_PATH_STORE, payload});
export const initRoutsNavigate = payload => ({ type: ActionTypes.INIT_ROUTS_NAVIGATE, payload });
export const setSelectedPeriod = payload => ({ type: ActionTypes.SET_SELECTED_PERIOD, payload });
export const setSettingsByUser = payload => ({ type: ActionTypes.SET_SETTINGS_BY_USER, payload });
export const showMoreInterests = payload => ({ type: ActionTypes.SHOW_MORE_INTERESTS, payload });
export const initAnotherUserId = () => ({ type: ActionTypes.INIT_ANOTHER_USER_ID });
export const setFoundInterests = payload => ({ type: ActionTypes.SET_FOUND_INTERESTS, payload });
export const setLikesDataStore = payload => ({ type: ActionTypes.SET_LIKES_DATA_STORE, payload });
export const setUserPinFilters = payload => ({ type: ActionTypes.SET_USER_PIN_FILTERS, payload });
export const removeFromFriends = payload => ({ type: ActionTypes.REMOVE_FROM_FRIENDS, payload });
export const sendFriendRequest = payload => ({ type: ActionTypes.SEND_FRIEND_REQUEST, payload });
export const errorNotification = payload => ({ type: ActionTypes.ERROR_NOTIFICATION, payload });
export const setChangePassword = payload => ({ type: ActionTypes.SET_CHANGE_PASSWORD, payload });
export const setSendGiftParams = payload => ({ type: ActionTypes.SET_SEND_GIFT_PARAMS, payload });
export const setLikeStatusStore = payload => ({ type: ActionTypes.SET_LIKE_STATUS_STORE, payload });
export const onClickLogInButton = payload => ({type: ActionTypes.ON_CLICK_LOG_IN_BUTTON, payload});
export const onCloseModalWindow = payload => ({ type: ActionTypes.ON_CLOSE_MODAL_WINDOW, payload });
export const setEditUserProfile = payload => ({ type: ActionTypes.SET_EDIT_USER_PROFILE, payload });
export const setEmailValueStore = payload => ({type: ActionTypes.SET_EMAIL_VALUE_STORE, payload});
export const onRegistrationClick = payload => ({ type: ActionTypes.ON_REGISTRATION_CLICK, payload });
export const setUserCountryStore = payload => ({type: ActionTypes.SET_USER_COUNTRY_STORE, payload});
export const setUserProfileStore = payload => ({type: ActionTypes.SET_USER_PROFILE_STORE, payload});
export const setButtonStateStore = payload => ({type: ActionTypes.SET_BUTTON_STATE_STORE, payload});
export const setResPasswordState = payload => ({type: ActionTypes.SET_RES_PASSWORD_STATE, payload})
export const sendEncodingRequest = payload => ({ type: ActionTypes.SEND_ENCODING_REQUEST, payload });
export const setUserPinFiltersLS = payload => ({ type: ActionTypes.SET_USER_PIN_FILTERS_LS, payload });
export const acceptFriendRequest = (payload, userId) => ({ type: ActionTypes.ACCEPT_FRIEND_REQUEST, payload, userId });
export const setSelectedLanguage = payload => ({ type: ActionTypes.SET_SELECTED_LANGUAGE, payload });
export const setStringsDataStore = payload => ({ type: ActionTypes.SET_STRINGS_DATA_STORE, payload });
export const updateStringsDataLS = payload => ({ type: ActionTypes.UPDATE_STRINGS_DATA_LS, payload });
export const sendCountersRequest = payload => ({ type: ActionTypes.SEND_COUNTERS_REQUEST, payload });
export const getGiftsByUserStore = payload => ({ type: ActionTypes.GET_GIFTS_BY_USER_STORE, payload });
export const setSelectedLocation = payload => ({ type: ActionTypes.SET_SELECTED_LOCATION, payload });
export const setUserPinDataStore = payload => ({ type: ActionTypes.SET_USER_PIN_DATA_STORE, payload });
export const setUserGalleryStore = payload => ({ type: ActionTypes.SET_USER_GALLERY_STORE, payload });
export const setShowNotification = payload => ({ type: ActionTypes.SET_SHOW_NOTIFICATION, payload });
export const declineFriendRequest = (payload, userId) => ({ type: ActionTypes.DECLINE_FRIEND_REQUEST, payload, userId });
export const setUserQuestionnaire = payload => ({type: ActionTypes.SET_USER_QUESTIONNAIRE, payload});
export const setRoutsHistoryStore = payload => ({ type: ActionTypes.SET_ROUTS_HISTORY_STORE, payload });
export const setFriendStatusStore = payload => ({ type: ActionTypes.SET_FRIEND_STATUS_STORE, payload });
export const getLikeStatusRequest = payload => ({ type: ActionTypes.GET_LIKE_STATUS_REQUEST, payload });
export const addLikeButtonOnClick = () => ({ type: ActionTypes.ADD_LIKE_BUTTON_ON_CLICK });
export const setCountersDataStore = payload => ({ type: ActionTypes.SET_COUNTERS_DATA_STORE, payload });
export const setPropertiesRequest = payload => ({ type: ActionTypes.SET_PROPERTIES_REQUEST, payload });
export const setAllInterestsStore = payload => ({ type: ActionTypes.SET_ALL_INTERESTS_STORE, payload });
export const setOnUserRiseRequest = payload => ({ type: ActionTypes.SET_ON_USER_RISE_REQUEST, payload });
export const setTopInterestsStore = payload => ({ type: ActionTypes.SET_TOP_INTERESTS_STORE, payload });
export const setSideMenuModeStore = payload => ({ type: ActionTypes.SET_SIDE_MENU_MODE_STORE, payload });
export const setInputBirthdayState = payload => ({type: ActionTypes.SET_INPUT_BIRTHDAY_STATE, payload});
export const setBothLikesDataStore = payload => ({ type: ActionTypes.SET_BOTH_LIKES_DATA_STORE, payload });
export const setFriendsListRequest = payload => ({ type: ActionTypes.SET_FRIENDS_LIST_REQUEST, payload });
export const setCurrentSearchField = payload => ({ type: ActionTypes.SET_CURRENT_SEARCH_FIELD_STORE, payload });
export const getUserPinListRequest = payload => ({ type: ActionTypes.GET_USER_PIN_LIST_REQUEST, payload });
export const setWindowScrollYStore = payload => ({ type: ActionTypes.SET_WINDOW_SCROLL_Y_STORE, payload });
export const getAnotherUserRequest = payload => ({ type: ActionTypes.GET_ANOTHER_USER_REQUEST, payload });
export const setNoEmailButtonState = payload => ({type: ActionTypes.SET_NO_EMAIL_BUTTON_STATE, payload});
export const setPasswordValueStore = payload => ({type: ActionTypes.SET_PASSWORD_VALUE_STORE, payload});
export const setRootComponentStore = payload => ({ type: ActionTypes.SET_ROOT_COMPONENT_STORE, payload });
export const setStyleValidateEmail = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_EMAIL, payload});
export const setInputTextPassStore = payload => ({type: ActionTypes.SET_INPUT_TEXT_PASS_STORE, payload});
export const setBirthdayByUserData = payload => ({ type: ActionTypes.SET_BIRTHDAY_BY_USER_DATA, payload });
export const addFriendButtonOnClick = () => ({ type: ActionTypes.ADD_FRIEND_BUTTON_ON_CLICK });
export const setUserPinFiltersStore = payload => ({ type: ActionTypes.SET_USER_PIN_FILTERS_STORE, payload });
export const deleteShowNotification = payload => ({ type: ActionTypes.DELETE_SHOW_NOTIFICATION, payload });
export const setSelectedPeriodStore = payload => ({ type: ActionTypes.SET_SELECTED_PERIOD_STORE, payload });
export const changeModalWindowState = payload => ({ type: ActionTypes.CHANGE_MODAL_WINDOW_STATE, payload });
export const setIsIdbAvailableStore = payload => ({ type: ActionTypes.SET_IS_IDB_AVAILABLE_STORE, payload });
export const setPropertiesDataStore = payload => ({ type: ActionTypes.SET_PROPERTIES_DATA_STORE, payload });
export const setFoundInterestsStore = payload => ({ type: ActionTypes.SET_FOUND_INTERESTS_STORE, payload });
export const setSaveInterestsByUser = payload => ({type: ActionTypes.SET_SAVE_INTERESTS_BY_USER, payload});
export const initDataByLocalStorage = payload => ({ type: ActionTypes.INIT_DATA_BY_LOCAL_STORAGE, payload });
export const openAnotherUserProfile = payload => ({ type: ActionTypes.OPEN_ANOTHER_USER_PROFILE, payload });
export const setMyProfileStateStore = payload => ({ type: ActionTypes.SET_MY_PROFILE_STATE_STORE, payload });
export const getFriendStatusRequest = payload => ({ type: ActionTypes.GET_FRIEND_STATUS_REQUEST, payload });
export const setParsedNotifications = payload => ({ type: ActionTypes.SET_PARSED_NOTIFICATIONS, payload });
export const getSettingsByUserStore = payload => ({ type: ActionTypes.GET_SETTINGS_BY_USER_STORE, payload });
export const setConstantValuesStore = payload => ({type: ActionTypes.SET_CONSTANT_VALUES_STORE, payload});
export const setPageEventsDataStore = payload => ({type: ActionTypes.SET_PAGE_EVENTS_DATA_STORE, payload});
export const setInputTextEmailStore = payload => ({type: ActionTypes.SET_INPUT_TEXT_EMAIL_STORE, payload});
export const setSettingsByUserStore = payload => ({ type: ActionTypes.SET_SETTINGS_BY_USER_STORE, payload });
export const setResPasswordInputText = payload => ({type:ActionTypes.SET_RES_PASSWORD_INPUT_TEXT, payload});
export const setIdbInitialStateStore = payload => ({ type: ActionTypes.SET_IDB_INITIAL_STATE_STORE, payload });
export const setResPasswordUserEmail = payload => ({type:ActionTypes.SET_RES_PASSWORD_USER_EMAIL, payload});
export const setResPasswordReCAPTCHA = payload => ({type:ActionTypes.SET_RES_PASSWORD_RECAPTCHA, payload});
export const setInterestsByUserStore = payload => ({ type: ActionTypes.SET_INTERESTS_BY_USER_STORE, payload });
export const initPlatformStringsData = payload => ({ type: ActionTypes.INIT_PLATFORM_STRINGS_DATA, payload });
export const submitUserPinFilterData = payload => ({ type: ActionTypes.SUBMIT_USER_PIN_FILTER_DATA, payload });
export const setEditUserProfileStore = payload => ({ type: ActionTypes.SET_EDIT_USER_PROFILE_STORE, payload });
export const setBalanceResponseStore = payload => ({ type: ActionTypes.SET_BALANCE_RESPONSE_STORE, payload });
export const setSelectedLanguageToLS = payload => ({ type: ActionTypes.SET_SELECTED_LANGUAGE_TO_LS, payload });
export const setResPasswordStateStore = payload => ({type: ActionTypes.SET_RES_PASSWORD_STATE_STORE, payload})
export const setReCAPTCHARegistration = payload => ({type: ActionTypes.SET_RECAPTCHA_REGISTRATION, payload});
export const setStyleValidatePassword = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_PASSWORD, payload});
export const sendActivityCheckRequest = payload => ({ type: ActionTypes.SEND_ACTIVITY_CHECK_REQUEST, payload });
export const setSelectedLanguageStore = payload => ({ type: ActionTypes.SET_SELECTED_LANGUAGE_STORE, payload });
export const setProfileRemovalRequest = payload => ({ type: ActionTypes.SET_PROFILE_REMOVAL_REQUEST, payload });
export const setGiftsVisibilityByUser = payload => ({ type: ActionTypes.SET_SETTINGS_GIFTS_VISIBILITY_BY_USER, payload });
export const resendLinkForVerifyEmail = payload => ({ type: ActionTypes.RESEND_LINK_FOR_VERIFY_EMAIL, payload });
export const createNotificationWindow = payload => ({type: ActionTypes.CREATE_NOTIFICATION_WINDOW, payload});
export const setSelectedLocationStore = payload => ({ type: ActionTypes.SET_SELECTED_LOCATION_STORE, payload });
export const setInterestEditingWindow = payload => ({ type: ActionTypes.SET_INTEREST_EDITING_WINDOW, payload });
export const setWindowScrollYPosition = () => ({type: ActionTypes.SET_WINDOW_SCROLL_Y_POSITION});
export const setNotificationsListData = payload => ({ type: ActionTypes.SET_NOTIFICATIONS_LIST_DATA, payload });
export const setInputFormattedBirthday = payload => ({type: ActionTypes.SET_INPUT_FORMATTED_BIRTHDAY_VALUE, payload});
export const setUserQuestionnaireStore = payload => ({type: ActionTypes.SET_USER_QUESTIONNAIRE_STORE, payload});
export const informationalNotification = payload => ({ type: ActionTypes.INFORMATIONAL_NOTIFICATION, payload });
export const setResPasswordButtonState = payload => ({type:ActionTypes.SET_RES_PASSWORD_BUTTON_STATE, payload});
export const setAnotherUserProfileData = payload => ({ type: ActionTypes.SET_ANOTHER_USER_PROFILE_DATA, payload });
export const setSelectedCityIdInFilter = payload => ({ type: ActionTypes.SET_SELECTED_CITY_ID_IN_FILTER, payload });
export const setAddInterestsListByUser = payload => ({ type: ActionTypes.SET_ADD_INTERESTS_LIST_BY_USER, payload });
export const setTimerAnotherUserButton = payload => ({ type: ActionTypes.SET_TIMER_ANOTHER_USER_BUTTON, payload });
export const setNotificationsIsWasRead = payload => ({ type: ActionTypes.SET_NOTIFICATIONS_IS_WAS_READ, payload });
export const setAnotherUserGalleryStore = payload => ({ type: ActionTypes.SET_ANOTHER_USER_GALLERY_STORE, payload });
export const setBirthdayByUserDataStore = payload => ({ type: ActionTypes.SET_BIRTHDAY_BY_USER_DATA_STORE, payload });
export const setFriendsVisibilityByUser = payload => ({ type: ActionTypes.SET_SETTINGS_FRIENDS_VISIBILITY_BY_USER, payload });
export const setSelectedLanguagesByUser = payload => ({ type: ActionTypes.SET_SELECTED_LANGUAGES_BY_USER, payload });
export const setFriendsListRequestStore = payload => ({ type: ActionTypes.SET_FRIENDS_LIST_REQUEST_STORE, payload });
export const setGiftsListDataPrimeStore = payload => ({ type: ActionTypes.SET_GIFTS_LIST_DATA_PRIME_STORE, payload });
export const setGiftsByAnotherUserStore = payload => ({ type: ActionTypes.SET_GIFTS_BY_ANOTHER_USER_STORE, payload });
export const setStyleValidateEmailStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_EMAIL_STORE, payload});
export const startInitModelDataRequests = payload => ({ type: ActionTypes.START_INIT_MODEL_DATA_REQUESTS, payload });
export const setNoEmailButtonStateStore = payload => ({type: ActionTypes.SET_NO_EMAIL_BUTTON_STATE_STORE, payload});
export const setChangePoseForSelfieStore = payload => ({ type: ActionTypes.SET_CHANGE_POSE_FOR_SELFIE_STORE, payload });
export const checkVerifyEmailAfterChange = payload => ({ type: ActionTypes.CHECK_VERIFY_EMAIL_AFTER_CHANGE, payload });
export const setLanguagesByUserDataStore = payload => ({ type: ActionTypes.SET_LANGUAGES_BY_USER_DATA_STORE, payload });
export const setNewEmailAfterChangeStore = payload => ({ type: ActionTypes.SET_NEW_EMAIL_AFTER_CHANGE_STORE, payload });
export const setParsedNotificationsStore = payload => ({ type: ActionTypes.SET_PARSED_NOTIFICATIONS_STORE, payload });
export const setInterestsCategoriesStore = payload => ({ type: ActionTypes.SET_INTERESTS_CATEGORIES_STORE, payload });
export const setILikedNotificationsStore = payload => ({ type: ActionTypes.SET_I_LIKED_NOTIFICATIONS_STORE, payload });
export const setFriendsRequestListRequest = payload => ({ type: ActionTypes.SET_FRIENDS_REQUEST_LIST_REQUEST, payload });
export const setShowNotificationListStore = payload => ({ type: ActionTypes.SET_SHOW_NOTIFICATION_LIST_STORE, payload });
export const setSelectedCategoryByTheUser = payload => ({ type: ActionTypes.SET_SELECTED_CATEGORY_BY_THE_USER, payload });
export const setClearShowNotificationList = payload => ({ type: ActionTypes.SET_CLEAR_SHOW_NOTIFICATIONS_LIST, payload });
export const getSelectedUserPublicGallery = payload => ({ type: ActionTypes.GET_SELECTED_USER_PUBLIC_GALLERY, payload });
export const setDeleteInterestsListByUser = payload => ({ type: ActionTypes.SET_DELETE_INTERESTS_LIST_BY_USER, payload });
export const setGenerateEmailLinkWithCode = payload => ({ type: ActionTypes.SET_GENERATE_EMAIL_LINK_WITH_CODE, payload });
export const setChangeEmailCodeErrorStore = payload => ({ type: ActionTypes.SET_CHANGE_EMAIL_CODE_ERROR_STORE, payload });
export const setResPasswordUserEmailStore = payload => ({type:ActionTypes.SET_RES_PASSWORD_USER_EMAIL_STORE, payload});
export const setResPasswordInputTextStore = payload => ({type:ActionTypes.SET_RES_PASSWORD_INPUT_TEXT_STORE, payload});
export const setResPasswordReCAPTCHAStore = payload => ({type:ActionTypes.SET_RES_PASSWORD_RECAPTCHA_STORE, payload});
export const setStateLocationRegistration = payload => ({type: ActionTypes.SET_STATE_LOCATION_REGISTRATION, payload});
export const setReCAPTCHARegistrationStore = payload => ({type: ActionTypes.SET_RECAPTCHA_REGISTRATION_STORE, payload});
export const setStyleValidatePasswordStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_PASSWORD_STORE, payload});
export const setPropertiesSelfiePoseByUser = payload => ({ type: ActionTypes.SET_PROPERTIES_SELFIE_POSE_BY_USER, payload });
export const setNotificationSystemInstance = payload => ({ type: ActionTypes.SET_NOTIFICATION_SYSTEM_INSTANCE, payload });
export const setIsFilterPeriodOpenDropDown = () => ({type: ActionTypes.SET_IS_FILTER_PERIOD_OPEN_DROP_DOWN});
export const setStringsDataTranslatesStore = payload => ({ type: ActionTypes.SET_STRINGS_DATA_TRANSLATES_STORE, payload });
export const setGiftsVisibilityByUserStore = payload => ({ type: ActionTypes.SET_SETTINGS_GIFTS_VISIBILITY_BY_USER_STORE, payload });
export const setPlatformLanguagesDataStore = payload => ({ type: ActionTypes.SET_PLATFORM_LANGUAGES_DATA_STORE, payload });
export const setGiftsListDataLowCoastStore = payload => ({ type: ActionTypes.SET_GIFTS_LIST_DATA_LOW_COAST_STORE, payload });
export const setInterestEditingWindowStore = payload => ({ type: ActionTypes.SET_INTEREST_EDITING_WINDOW_STORE, payload });
export const setResPasswordButtonStateStore = payload => ({type:ActionTypes.SET_RES_PASSWORD_BUTTON_STATE_STORE, payload});
export const setSearchCityValueRegistration = payload => ({type: ActionTypes.SET_SEARCH_CITY_VALUE_REGISTRATION, payload});
export const setSelectedCityIdInFilterStore = payload => ({ type: ActionTypes.SET_SELECTED_CITY_ID_IN_FILTER_STORE, payload });
export const setAnotherUserFriendsListStore = payload => ({ type: ActionTypes.SET_ANOTHER_USER_FRIENDS_LIST_STORE, payload });
export const setAddInterestsListByUserStore = payload => ({ type: ActionTypes.SET_ADD_INTERESTS_LIST_BY_USER_STORE, payload });
export const setInterestsByAnotherUserStore = payload => ({ type: ActionTypes.SET_INTERESTS_BY_ANOTHER_USER_STORE, payload });
export const setAnotherUserProfileDataStore = payload => ({ type: ActionTypes.SET_ANOTHER_USER_PROFILE_DATA_STORE, payload });
export const setNotificationsEventIsWasRead = payload => ({ type: ActionTypes.SET_NOTIFICATIONS_EVENT_IS_WAS_READ, payload });
export const setPaginationInterestDataStore = payload => ({ type: ActionTypes.SET_PAGINATION_INTEREST_DATA_STORE, payload });
export const setFriendsVisibilityByUserStore = payload => ({ type: ActionTypes.SET_SETTINGS_FRIENDS_VISIBILITY_BY_USER_STORE, payload });
export const setGeneratePasswordLinkWithCode = payload => ({ type: ActionTypes.SET_GENERATE_PASSWORD_LINK_WITH_CODE, payload });
export const setChangePasswordCodeErrorStore = payload => ({ type: ActionTypes.SET_CHANGE_PASSWORD_CODE_ERROR_STORE, payload });
export const setNotificationsEventsListStore = payload => ({ type: ActionTypes.SET_NOTIFICATIONS_EVENTS_LIST_STORE, payload });
export const sendCheckIsActiveContentRequest = payload => ({type: ActionTypes.SEND_CHECK_IS_ACTIVE_CONTENT_REQUEST, payload});
export const setGiftsListDataMiddleCoastStore = payload => ({ type: ActionTypes.SET_GIFTS_LIST_DATA_MIDLE_COAST_STORE, payload });
export const setAnotherUserButtonsTimersStore = payload => ({ type: ActionTypes.SET_ANOTHER_USER_BUTTONS_TIMERS_STORE, payload });
export const setGiftsStatusByAnotherUserStore = payload => ({ type: ActionTypes.SET_GIFTS_STATUS_BY_ANOTHER_USER_STORE, payload });
export const setResPasswordStyleValidateEmail = payload => ({type: ActionTypes.SET_RES_PASSWORD_STYLE_VALIDATE_EMAIL, payload});
export const setStyleValidateEmailRegistration = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_EMAIL_REGISTRATION, payload});
export const setStateLocationRegistrationStore = payload => ({type: ActionTypes.SET_STATE_LOCATION_REGISTRATION_STORE, payload});
export const setFriendsRequestListRequestStore = payload => ({ type: ActionTypes.SET_FRIENDS_REQUEST_LIST_REQUEST_STORE, payload });
export const setSelectedCategoryByTheUserStore = payload => ({ type: ActionTypes.SET_SELECTED_CATEGORY_BY_THE_USER_STORE, payload });
export const setDeleteInterestsListByUserStore = payload => ({ type: ActionTypes.SET_DELETE_INTERESTS_LIST_BY_USER_STORE, payload });
export const setLanguagesByAnotherUserDataStore = payload => ({type: ActionTypes.SET_LANGUAGES_BY_ANOTHER_USER_DATA_STORE, payload});
export const setIsFilterPeriodOpenDropDownStore = payload => ({type: ActionTypes.SET_IS_FILTER_PERIOD_OPEN_DROP_DOWN_STORE, payload});
export const setAnotherUserProfileDataClearStore = payload => ({ type: ActionTypes.SET_ANOTHER_USER_PROFILE_DATA_CLEAR_STORE, payload });
export const setFormattedBirthdayByUserDataStore = payload => ({ type: ActionTypes.SET_FORMATTED_BIRTHDAY_BY_USER_DATA_STORE, payload });
export const setSearchCityValueRegistrationStore = payload => ({type: ActionTypes.SET_SEARCH_CITY_VALUE_REGISTRATION_STORE, payload});
export const setStyleValidatePasswordRegistration = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_PASSWORD_REGISTRATION, payload});
export const setStyleValidateUserNameRegistration = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_USER_NAME_REGISTRATION, payload});
export const startCheckContentIsActiveStatusTimer = payload => ({ type: ActionTypes.START_CHECK_CONTENT_IS_ACTIVE_STATUS_TIMER, payload });
export const setVisitorsListBySelectedPeriodStore = payload => ({ type: ActionTypes.SET_VISITORS_LIST_BY_SELECTED_PERIOD_STORE, payload });
export const setTemporaryInterestsListByUserStore = payload => ({ type: ActionTypes.SET_TEMPORARY_INTERESTS_LIST_BY_USER_STORE, payload });
export const sendNotificationEventsNotWasReedList = payload => ({ type: ActionTypes.SEND_NOTIFICATION_EVENTS_NOT_WAS_REED_LIST, payload });
export const setChangeUserStatusAfterVerification = payload => ({ type: ActionTypes.SET_CHANGE_USER_STATUS_AFTER_VERIFICATION_STORE, payload });
export const setResPasswordStyleValidateEmailStore = payload => ({type: ActionTypes.SET_RES_PASSWORD_STYLE_VALIDATE_EMAIL_STORE, payload});
export const setValidateCitySelectValueRegistration = payload => ({type: ActionTypes.SET_VALIDATE_CITY_SELECT_VALUE_REGISTRATION, payload});
export const setStyleValidateDayOfBirthRegistration = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_DAY_OF_BIRTH_REGISTRATION, payload});
export const setStyleValidateEmailRegistrationStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_EMAIL_REGISTRATION_STORE, payload});
export const setUserGalleryNotActiveContentIdsStore = payload => ({ type: ActionTypes.SET_USER_GALLERY_NOT_ACTIVE_CONTENT_IDS_STORE, payload });
export const getVisitorsListBySelectedPeriodRequest = payload => ({type: ActionTypes.GET_VISITORS_LIST_BY_SELECTED_PERIOD_REQUEST, payload});
export const setFilteredAddInterestsListByUserStore = payload => ({ type: ActionTypes.SET_FILTERED_ADD_INTERESTS_LIST_BY_USER_STORE, payload });
export const setScrollTopNotificationContainerStore = payload => ({ type: ActionTypes.SET_SCROLL_TOP_NOTIFICATION_CONTAINER_STORE, payload });
export const setAddTemporaryInterestsListByUserStore = payload => ({ type: ActionTypes.SET_ADD_TEMPORARY_INTERESTS_LIST_BY_USER_STORE, payload });
export const setCurrentInterestsOfTheSelectedCategory = payload => ({ type: ActionTypes.SET_CURRENT_INTERESTS_OF_THE_SELECTED_CATEGORY, payload });
export const startTimerForCheckVerifyEmailAfterChange = payload => ({ type: ActionTypes.START_TIMER_FOR_CHECK_VERIFY_EMAIL_AFTER_CHANGE, payload });
export const setFilteredDeleteInterestsListByUserStore = payload => ({ type: ActionTypes.SET_FILTERED_DELETE_INTERESTS_LIST_BY_USER_STORE, payload });
export const setStyleValidatePasswordRegistrationStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_PASSWORD_REGISTRATION_STORE, payload});
export const setStyleValidateUserNameRegistrationStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_USER_NAME_REGISTRATION_STORE, payload});
export const setValidateCitySelectValueRegistrationStore = payload => ({type: ActionTypes.SET_VALIDATE_CITY_SELECT_VALUE_REGISTRATION_STORE, payload});
export const setStyleValidateDayOfBirthRegistrationStore = payload => ({type: ActionTypes.SET_STYLE_VALIDATE_DAY_OF_BIRTH_REGISTRATION_STORE, payload});
export const startAnotherUserAddFriendAndLikeUserButtonsTimer = () => ({ type: ActionTypes.START_ANOTHER_USER_ADD_FRIEND_AND_LIKE_USER_BUTTONS_TIMER });


